// Writes the TypeScript and Python modules that carry package.json's version and
// the registry (registry/*.json) into each implementation. Run with --check to
// fail when a generated file is stale instead of writing it.
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'

const root = new URL('../', import.meta.url)
const read = (path: string) => JSON.parse(readFileSync(new URL(path, root), 'utf8'))

const { version } = read('package.json')
const { reasons } = read('registry/reasons.json') as { reasons: { id: string }[] }
const { signers } = read('registry/signers.json') as { signers: Record<string, string> }
const { tokens } = read('registry/tokens.json') as { tokens: { token: string; name: string }[] }
const page = read('registry/page.json') as {
  user_agent_prefixes: Record<string, string>
  platforms: Record<string, string>
}
const keys = read('registry/keys.json') as {
  fetched_at: string
  directories: Record<string, { x: string; kid?: string; nbf?: number; exp?: number }[]>
}

const json = (value: unknown) => JSON.stringify(value)
// RFC 7638 thumbprint of an Ed25519 JWK: SHA-256 over the required members in
// lexicographic order, base64url. Web Bot Auth keyids are these thumbprints.
const thumbprint = (x: string) =>
  createHash('sha256').update(`{"crv":"Ed25519","kty":"OKP","x":"${x}"}`).digest('base64url')
const keyEntries = Object.fromEntries(
  Object.entries(keys.directories).map(([host, list]) => [
    host,
    list.map(({ x, kid, nbf, exp }) => ({
      x,
      thumbprint: thumbprint(x),
      kid: kid ?? null,
      nbf: nbf ?? null,
      exp: exp ?? null,
    })),
  ]),
)

const header = `// Generated by scripts/generate.ts from package.json and registry/. Do not edit.\n`

const core = `${header}
export const VERSION: string = ${json(version)}

/** Reason ids, strongest first (registry/reasons.json). */
export const REASONS: readonly KnownReason[] = ${json(reasons.map((r) => r.id))}
export type KnownReason =
${reasons.map((r) => `  | ${json(r.id)}`).join('\n')}
`

const server = `${header}
/** Web Bot Auth signer host -> operator-level name (registry/signers.json). */
export const SIGNERS: Readonly<Record<string, string>> = ${json(signers)}

/** Declared user-agent tokens and the names they give, in registry order (registry/tokens.json). */
export const TOKENS: readonly (readonly [token: string, name: string])[] = ${json(tokens.map((t) => [t.token, t.name]))}

/** Bundled Ed25519 keys per signer host, fetched ${keys.fetched_at} (registry/keys.json). */
export const KEYS: Readonly<Record<string, readonly SignerKey[]>> = ${json(keyEntries)}
export type SignerKey = { x: string; thumbprint: string; kid: string | null; nbf: number | null; exp: number | null }
`

const pageData = `${header}
/** What a page's own navigator can declare (registry/page.json). */
export const PAGE_USER_AGENT_PREFIXES: Readonly<Record<string, string>> = ${json(page.user_agent_prefixes)}
export const PAGE_PLATFORMS: Readonly<Record<string, string>> = ${json(page.platforms)}
`

// Python literals: JSON strings and numbers are valid Python; null, true and false are not.
const py = (value: unknown): string => {
  if (value === null || value === undefined) return 'None'
  if (value === true) return 'True'
  if (value === false) return 'False'
  if (typeof value === 'string' || typeof value === 'number') return JSON.stringify(value)
  if (Array.isArray(value)) return `[${value.map(py).join(', ')}]`
  return `{${Object.entries(value as object)
    .map(([k, v]) => `${JSON.stringify(k)}: ${py(v)}`)
    .join(', ')}}`
}
const python = `# Generated by scripts/generate.ts from package.json and registry/. Do not edit.

VERSION = ${json(version)}

# Reason ids, strongest first (registry/reasons.json).
REASONS = (${reasons.map((r) => json(r.id)).join(', ')},)

# Web Bot Auth signer host -> operator-level name (registry/signers.json).
SIGNERS = ${py(signers)}

# Declared user-agent tokens and the names they give, in registry order (registry/tokens.json).
TOKENS = (${tokens.map((t) => `(${json(t.token)}, ${json(t.name)})`).join(', ')},)

# Bundled Ed25519 keys per signer host, fetched ${keys.fetched_at} (registry/keys.json).
KEYS = ${py(keyEntries)}
`

const outputs: [string, string][] = [
  ['src/generated/core.ts', core],
  ['src/generated/server.ts', server],
  ['src/generated/page.ts', pageData],
  ['python/src/botscent/_generated.py', python],
]
const check = process.argv.includes('--check')
let stale = 0
for (const [path, content] of outputs) {
  const url = new URL(path, root)
  let current = ''
  try {
    current = readFileSync(url, 'utf8')
  } catch {}
  if (current === content) continue
  if (check) {
    console.error(`stale: ${path} (run npm run generate)`)
    stale++
  } else {
    writeFileSync(url, content)
    console.log(`wrote ${path}`)
  }
}
if (stale) process.exit(1)
