# Generated by scripts/generate.ts from package.json and registry/. Do not edit.

VERSION = "0.0.0"

# Reason ids, strongest first (registry/reasons.json).
REASONS = ("signer.web-bot-auth.verified", "signer.edge-verified-bot", "signer.web-bot-auth.declared", "ua.declared-agent-token", "ua.page-declared-engine", "browser.webdriver-flag", "ua.headless-chrome", "muse.credentials.accessor-family", "instinct.credentials.wrappers", "instinct.geetest.accessor-pair", "codex.prompt.anonymous-native", "codex.keyboard.empty-layout-map", "codex.overlay.shadow-root", "chatgpt.badge.active", "claude.marker.active", "hidden.input.focus-emulated", "hidden.input.trusted-pointerdown",)

# Web Bot Auth signer host -> operator-level name (registry/signers.json).
SIGNERS = {"chatgpt.com": "chatgpt", "cursorusercontent.com": "cursor", "api.manus.im": "manus", "web-bot-auth.cloudflare-browser-rendering-085.workers.dev": "cloudflare-browser-run"}

# Declared user-agent tokens and the names they give, in registry order (registry/tokens.json).
TOKENS = (("Devin", "devin"), ("Manus-User", "manus"), ("botscent-check", "botscent-check"),)

# Bundled Ed25519 keys per signer host, fetched 2026-10-01T14:10:00Z (registry/keys.json).
KEYS = {"chatgpt.com": [{"x": "P_1c4SX6fCavDcq6FRegWcVvaOKsp_aXHPEN1FcKDIA", "thumbprint": "ArwjqcCqtA5oxEWkzXGC-To_0A9whHmajCHtfe8I9aY", "kid": "ArwjqcCqtA5oxEWkzXGC-To_0A9whHmajCHtfe8I9aY", "nbf": 1735689600, "exp": 1791468407}], "cursorusercontent.com": [{"x": "STDZXOMW-Cg7paRpv_BtjujEHIQVNbzidfjY9M9w6hc", "thumbprint": "Vuxu4khgzIe0b30Nd6hq2envAuVBFMTDqorSNIUb_Oo", "kid": "Vuxu4khgzIe0b30Nd6hq2envAuVBFMTDqorSNIUb_Oo", "nbf": 1786403101, "exp": 1817939101}], "api.manus.im": [{"x": "KcGM6sqzNes25V0hn96KsrIwL6pbut1KQMGmyFwpboM", "thumbprint": "Xk_eOiOd9LOoBlPDuVGzORLcYvjm7zxBkaYHFsP6J_I", "kid": None, "nbf": None, "exp": None}], "web-bot-auth.cloudflare-browser-rendering-085.workers.dev": [{"x": "pv_pTt9kUUO_1vl4JGNEdVo6r42LvuXDEwnZJGLFDq4", "thumbprint": "QHrZVI7uYXBXsRaTTUojpmFG0UNelgU8-n5tmuRh08U", "kid": None, "nbf": None, "exp": None}, {"x": "c-5EYjQKU5ZO3uIfQL8xdvb9RKSHJNcGFB9beEpx824", "thumbprint": "3JVD-GUlusv36Msck-1m0nvGAwt3xBNNVIVqYe15CYU", "kid": None, "nbf": None, "exp": None}, {"x": "8znwZmIRuD6s4tQ54-OiPB32fY6k-XeyVsdU6aqFd_k", "thumbprint": "WdHpbKqU_Xqe-C5zUhXY9yUAuggIzqebBWFV04NEcpc", "kid": None, "nbf": None, "exp": None}]}
