// Generated by scripts/generate.ts from package.json and registry/. Do not edit.

export const VERSION: string = "0.0.0"

/** Reason ids, strongest first (registry/reasons.json). */
export const REASONS: readonly KnownReason[] = ["signer.web-bot-auth.verified","signer.edge-verified-bot","signer.web-bot-auth.declared","ua.declared-agent-token","ua.page-declared-engine","browser.webdriver-flag","ua.headless-chrome","muse.credentials.accessor-family","instinct.credentials.wrappers","instinct.geetest.accessor-pair","codex.prompt.anonymous-native","codex.keyboard.empty-layout-map","codex.overlay.shadow-root","chatgpt.badge.active","claude.marker.active","hidden.input.focus-emulated","hidden.input.trusted-pointerdown"]
export type KnownReason =
  | "signer.web-bot-auth.verified"
  | "signer.edge-verified-bot"
  | "signer.web-bot-auth.declared"
  | "ua.declared-agent-token"
  | "ua.page-declared-engine"
  | "browser.webdriver-flag"
  | "ua.headless-chrome"
  | "muse.credentials.accessor-family"
  | "instinct.credentials.wrappers"
  | "instinct.geetest.accessor-pair"
  | "codex.prompt.anonymous-native"
  | "codex.keyboard.empty-layout-map"
  | "codex.overlay.shadow-root"
  | "chatgpt.badge.active"
  | "claude.marker.active"
  | "hidden.input.focus-emulated"
  | "hidden.input.trusted-pointerdown"

/** Web Bot Auth signer host -> operator-level name (registry/signers.json). */
export const SIGNERS: Readonly<Record<string, string>> = {"chatgpt.com":"chatgpt","cursorusercontent.com":"cursor","api.manus.im":"manus","web-bot-auth.cloudflare-browser-rendering-085.workers.dev":"cloudflare-browser-run"}

/** Declared user-agent tokens and the names they give, in registry order (registry/tokens.json). */
export const TOKENS: readonly (readonly [token: string, name: string])[] = [["Devin","devin"],["Manus-User","manus"],["botscent-check","botscent-check"]]

/** What a page's own navigator can declare (registry/page.json). */
export const PAGE_USER_AGENT_PREFIXES: Readonly<Record<string, string>> = {"Kitesurf/":"cloudflare-browser-run"}
export const PAGE_PLATFORMS: Readonly<Record<string, string>> = {"Cloudflare Workers":"cloudflare-browser-run"}

/** Bundled Ed25519 keys per signer host, fetched 2026-10-01T14:10:00Z (registry/keys.json). */
export const KEYS: Readonly<Record<string, readonly SignerKey[]>> = {"chatgpt.com":[{"x":"P_1c4SX6fCavDcq6FRegWcVvaOKsp_aXHPEN1FcKDIA","kid":"ArwjqcCqtA5oxEWkzXGC-To_0A9whHmajCHtfe8I9aY","nbf":1735689600,"exp":1791468407}],"cursorusercontent.com":[{"x":"STDZXOMW-Cg7paRpv_BtjujEHIQVNbzidfjY9M9w6hc","kid":"Vuxu4khgzIe0b30Nd6hq2envAuVBFMTDqorSNIUb_Oo","nbf":1786403101,"exp":1817939101}],"api.manus.im":[{"x":"KcGM6sqzNes25V0hn96KsrIwL6pbut1KQMGmyFwpboM","kid":null,"nbf":null,"exp":null}],"web-bot-auth.cloudflare-browser-rendering-085.workers.dev":[{"x":"pv_pTt9kUUO_1vl4JGNEdVo6r42LvuXDEwnZJGLFDq4","kid":null,"nbf":null,"exp":null},{"x":"c-5EYjQKU5ZO3uIfQL8xdvb9RKSHJNcGFB9beEpx824","kid":null,"nbf":null,"exp":null},{"x":"8znwZmIRuD6s4tQ54-OiPB32fY6k-XeyVsdU6aqFd_k","kid":null,"nbf":null,"exp":null}]}
export type SignerKey = { x: string; kid: string | null; nbf: number | null; exp: number | null }
